mindsdb_sql/__about__.py, mindsdb_sql/planner/query_plan.py, mindsdb_sql/planner/steps.py, mindsdb_sql/planner/ts_utils.py, tests/test_planner/test_ts_predictor.py
New planner steps: MapReduceStep, MultipleSteps
=> Rework timeseries predictors: ts predictors perform queries for partition each separately

mindsdb_sql/parser/ast/set.py, mindsdb_sql/parser/dialects/mindsdb/parser.py, mindsdb_sql/parser/dialects/mysql/parser.py, mindsdb_sql/parser/parser.py, tests/test_parser/test_base_sql/test_misc_sql_queries.py
=> Add ability to use set expr, e.g. SET var = value, fix SET names

mindsdb_sql/parser/dialects/mindsdb/lexer.py, mindsdb_sql/parser/dialects/mindsdb/parser.py, mindsdb_sql/parser/dialects/mysql/parser.py, mindsdb_sql/parser/lexer.py, mindsdb_sql/parser/parser.py, tests/test_parser/test_base_sql/test_base_lexer.py, tests/test_parser/test_base_sql/test_select_structure.py, tests/test_parser/test_mindsdb/test_drop_predictor.py, tests/test_parser/test_mindsdb/test_retrain_predictor.py
=> Replace the way identifiers are built, handle tricky cases of keyword/id ambiguity without special cases

mindsdb_sql/__about__.py, mindsdb_sql/parser/dialects/mindsdb/parser.py, tests/test_parser/test_mindsdb/test_drop_predictor.py
=> Add DROP TABLE syntax to mindsdb dialect

mindsdb_sql/parser/dialects/mindsdb/parser.py, mindsdb_sql/parser/dialects/mysql/__init__.py, mindsdb_sql/parser/dialects/mysql/parser.py, mindsdb_sql/parser/dialects/mysql/show_index.py, mindsdb_sql/parser/logger.py, mindsdb_sql/parser/parser.py, tests/test_parser/test_base_sql/test_show.py, tests/test_parser/test_mindsdb/test_selects.py, tests/test_parser/test_mysql/test_mysql_parser.py
=> SELECT STATUS query fix, ability to silence SLY warnings, SHOW INDEX query for mysql

mindsdb_sql/parser/dialects/mindsdb/lexer.py, mindsdb_sql/parser/lexer.py, tests/test_parser/test_base_sql/test_base_lexer.py
=> Allow identifier names starting from 0, including dollar sign

mindsdb_sql/parser/ast/select/identifier.py, mindsdb_sql/parser/dialects/mindsdb/create_predictor.py, mindsdb_sql/parser/dialects/mindsdb/lexer.py, mindsdb_sql/parser/dialects/mindsdb/parser.py, mindsdb_sql/parser/lexer.py, tests/test_parser/test_base_sql/test_base_lexer.py, tests/test_parser/test_mindsdb/test_create_predictor.py, tests/test_parser/test_mindsdb/test_drop_predictor.py, tests/test_parser/test_mindsdb/test_retrain_predictor.py
=> Fix identifiers like `id` not being stripped properly

mindsdb_sql/parser/dialects/mindsdb/parser.py, tests/test_parser/test_mindsdb/test_create_integration.py
=> CREATE DATASOURCE: optional ',' and '='

mindsdb_sql/parser/dialects/mindsdb/parser.py, mindsdb_sql/parser/dialects/mysql/parser.py, tests/test_parser/test_base_sql/test_select_structure.py
fix #113
for mindsdb and mysql syntax
=> table can be named 'PLUGINS'

mindsdb_sql/planner/query_plan.py
Dot in alias fix #131
Constants as identifiers fix #133
=> Planner fixes

mindsdb_sql/parser/dialects/mindsdb/parser.py, tests/test_parser/test_mindsdb/test_create_predictor.py
USING
**model = 'params',
key2='params2'**
#153
=> CREATE PREDICTOR: changed syntax in USING

mindsdb_sql/__about__.py, mindsdb_sql/planner/query_prepare.py
Fix error: parameter not have attribute parts
=> Release 0.1.3

mindsdb_sql/planner/ts_utils.py, tests/test_parser/test_mindsdb/test_timeseries.py, tests/test_planner/test_ts_predictor.py
Reference issue [here](https://github.com/mindsdb/mindsdb/issues/2180).
=> Fix M#2180

mindsdb_sql/__about__.py, mindsdb_sql/parser/ast/select/__init__.py, mindsdb_sql/parser/ast/select/native_query.py, mindsdb_sql/parser/dialects/mindsdb/parser.py, mindsdb_sql/planner/query_planner.py, mindsdb_sql/planner/steps.py, tests/test_parser/test_mindsdb/test_selects.py, tests/test_planner/test_integration_select.py, tests/test_planner/test_join_predictor.py, tests/test_planner/test_prepared_statement.py
New Syntax to send queries to parent DB #215
=> Release 0.3.13

mindsdb_sql/__about__.py, mindsdb_sql/planner/query_planner.py, mindsdb_sql/planner/utils.py, tests/test_planner/test_prepared_statement.py, tests/test_planner/test_select_from_predictor.py, tests/test_planner/test_ts_predictor.py
Changed predictor metadata structure for support multiple ml handlers
=> Release 0.4.0

mindsdb_sql/__about__.py, mindsdb_sql/parser/ast/describe.py, mindsdb_sql/parser/dialects/mindsdb/parser.py, mindsdb_sql/planner/ts_utils.py, tests/test_parser/test_base_sql/test_describe.py, tests/test_planner/test_ts_predictor.py
Changes:
- 'describe predictor' command
- fix wrong timefilter using several group fields
=> Release 0.4.1

.github/workflows/pypi.yml, mindsdb_sql/__about__.py, mindsdb_sql/parser/ast/insert.py, mindsdb_sql/parser/ast/select/operation.py, mindsdb_sql/parser/ast/select/type_cast.py, mindsdb_sql/parser/ast/update.py, mindsdb_sql/parser/dialects/mindsdb/parser.py, mindsdb_sql/parser/dialects/mysql/parser.py, mindsdb_sql/parser/parser.py, mindsdb_sql/planner/query_planner.py, mindsdb_sql/planner/query_prepare.py, mindsdb_sql/planner/steps.py, mindsdb_sql/planner/utils.py, mindsdb_sql/render/sqlalchemy_render.py, tests/test_parser/test_base_sql/test_select_operations.py, tests/test_parser/test_base_sql/test_select_structure.py, tests/test_parser/test_base_sql/test_update.py, tests/test_planner/test_ts_predictor.py, tests/test_render/test_sqlalchemyrender.py
Changes:
- update command
- size on type cast
- support sql extract function
=> Release 0.4.2

mindsdb_sql/parser/dialects/mindsdb/__init__.py, mindsdb_sql/parser/dialects/mindsdb/create_database.py, mindsdb_sql/parser/dialects/mindsdb/parser.py, tests/test_parser/test_mindsdb/test_create_integration.py
=> update of CREATE DATABASE

mindsdb_sql/parser/dialects/mindsdb/__init__.py, mindsdb_sql/parser/dialects/mindsdb/adjust_predictor.py, mindsdb_sql/parser/dialects/mindsdb/lexer.py, mindsdb_sql/parser/dialects/mindsdb/parser.py, tests/test_parser/test_mindsdb/test_adjust_predictor.py
- Add support for `ADJUST` in Lexer + short unit test
- Add support for `ADJUST` in Parser + short unit test
=> Adjust support

mindsdb_sql/__about__.py, mindsdb_sql/parser/dialects/mindsdb/__init__.py, mindsdb_sql/parser/dialects/mindsdb/create_job.py, mindsdb_sql/parser/dialects/mindsdb/drop_job.py, mindsdb_sql/parser/dialects/mindsdb/lexer.py, mindsdb_sql/parser/dialects/mindsdb/parser.py, mindsdb_sql/planner/query_planner.py, requirements.txt, tests/test_parser/test_mindsdb/test_jobs.py, tests/test_planner/test_join_tables.py, tests/test_planner/test_select_from_predictor.py
Changes:
- Create/drop job syntax (https://github.com/mindsdb/mindsdb/issues/4227)
Fixes:
- #227
-  One-line prediction fails with version greater than 10
=> Release 0.4.8

mindsdb_sql/__about__.py, mindsdb_sql/parser/dialects/mindsdb/parser.py, mindsdb_sql/planner/query_planner.py, mindsdb_sql/planner/steps.py
Changes:
- Planner supports regular insert
Fixes:
- #198
=> Release 0.4.9 

mindsdb_sql/__about__.py, mindsdb_sql/parser/dialects/mindsdb/parser.py, mindsdb_sql/parser/dialects/mysql/parser.py, mindsdb_sql/parser/parser.py, tests/test_parser/test_base_sql/test_select_operations.py
Fix:
- using 'databases' keyword
=> Release 0.6.1

mindsdb_sql/__about__.py, mindsdb_sql/planner/query_planner.py, mindsdb_sql/planner/query_prepare.py, mindsdb_sql/planner/steps.py, tests/test_planner/test_integration_select.py, tests/test_planner/test_select_from_predictor.py
Changes:
- don't split query from same integration to substeps (#276 )
=> Release 0.6.5

mindsdb_sql/__about__.py, mindsdb_sql/parser/dialects/mindsdb/parser.py, mindsdb_sql/parser/dialects/mindsdb/trigger.py, mindsdb_sql/planner/query_planner.py, mindsdb_sql/planner/utils.py, sly/lex.py, tests/test_parser/test_mindsdb/test_triggers.py, tests/test_planner/test_join_predictor.py, tests/test_planner/test_select_from_predictor.py
Changes:
- Fix [UnboundLocalError: local variable 'pattern' referenced before...]( https://github.com/mindsdb/mindsdb_python_sdk/issues/60) in python SDK
- Updated Readme.md
- Trigger: column to subscribe
- Fix: pass predictor params in join with native query
- Fixed #271
- Fixed #262
=> Release 0.6.7

mindsdb_sql/parser/ast/base.py, mindsdb_sql/planner/query_planner.py
Fixed:
- accept BinaryOperation in project step
- expect not only Identifier on input of is_predictor
=> TimeGPT fixes:

mindsdb_sql/__about__.py, mindsdb_sql/parser/dialects/mindsdb/knowledge_base.py, mindsdb_sql/parser/dialects/mindsdb/parser.py, tests/test_parser/test_mindsdb/test_knowledgebase.py, tests/test_parser/test_mindsdb/test_selects.py
Changes:
- Add Support for 'agent' Param for CREATE Chatbot Command #307
- Fix parser to allow no storage to be passed to knowledge base #314
=> Release 0.7.3

mindsdb_sql/__about__.py, mindsdb_sql/parser/dialects/mindsdb/latest.py, mindsdb_sql/planner/query_planner.py, tests/test_planner/test_ts_predictor.py
=> Fix planner for TS models with `date =`

mindsdb_sql/__about__.py, mindsdb_sql/parser/dialects/mindsdb/knowledge_base.py, mindsdb_sql/parser/dialects/mindsdb/parser.py, tests/test_parser/test_mindsdb/test_knowledgebase.py
Changes:
- Fix planner for TS models with date = #335
=> Release 0.9.0

mindsdb_sql/__about__.py, mindsdb_sql/parser/ast/select/native_query.py
Fixes:
- fix native query render
=> Release 0.10.2

mindsdb_sql/parser/dialects/mindsdb/parser.py, tests/test_parser/test_mindsdb/test_knowledgebase.py
using is optional in CREATE KNOWLEDGE_BASE
=> CREATE KNOWLEDGE_BASE without using

mindsdb_sql/parser/ast/select/constant.py, mindsdb_sql/parser/ast/select/operation.py, mindsdb_sql/parser/ast/set.py, mindsdb_sql/parser/ast/show.py, mindsdb_sql/parser/dialects/mindsdb/chatbot.py, mindsdb_sql/parser/dialects/mindsdb/create_database.py, mindsdb_sql/parser/dialects/mindsdb/create_job.py, mindsdb_sql/parser/dialects/mindsdb/lexer.py, mindsdb_sql/parser/dialects/mindsdb/parser.py, mindsdb_sql/parser/dialects/mysql/parser.py, tests/test_parser/test_base_sql/test_misc_sql_queries.py, tests/test_parser/test_base_sql/test_show.py, tests/test_parser/test_mindsdb/test_create_view.py, tests/test_parser/test_mindsdb/test_selects.py, tests/test_parser/test_standard_render.py
=> Parser fixes 02.2024

mindsdb_sql/__about__.py
Empty release to update version to 0.11.0
=> Release 0.11.0

mindsdb_sql/render/sqlalchemy_render.py
Render 'delete from table' with sqlalchemy render
=> Render Delete command

mindsdb_sql/parser/dialects/mindsdb/knowledge_base.py, tests/test_parser/test_mindsdb/test_knowledgebase.py
- fixes kb render
- include kb to standart render tests
=> Fixes KB render

mindsdb_sql/__about__.py, mindsdb_sql/planner/plan_join.py, mindsdb_sql/planner/steps.py, tests/test_planner/test_join_predictor.py
Changes:
- Model column mapping #375
=> Release 0.15.0

mindsdb_sql/parser/dialects/mindsdb/parser.py
Changes:
- agent for model is optional
Required for: https://github.com/mindsdb/mindsdb/pull/9481
=> Model of an agent is optional

mindsdb_sql/parser/dialects/mindsdb/lexer.py, mindsdb_sql/parser/dialects/mindsdb/parser.py, tests/test_parser/test_mindsdb/test_selects.py
- support match/not match
part of #388
=> Support match/not match (pg syntax)

mindsdb_sql/parser/ast/select/operation.py, mindsdb_sql/render/sqlalchemy_render.py, tests/test_parser/test_base_sql/test_misc_sql_queries.py
Interval format is
- INTERVAL '1' day
It is supported by PG and mysql
=> Change interval render 

mindsdb_sql/render/sqlalchemy_render.py
Fix sqlalchemy render: check type of col.type before comparing
=> Fix sqlalchemy render

mindsdb_sql/__about__.py, mindsdb_sql/render/sqlalchemy_render.py
=> Release 0.18.1

mindsdb_sql/planner/query_planner.py
LLM function is custom function, similar as byom functions
=> Support llm function

mindsdb_sql/parser/ast/select/operation.py, mindsdb_sql/render/sqlalchemy_render.py
Fixes
- fix standard render 'interval': number have to be quoted
- fix case with default value for sqlachemy render
=> Parser fixes #2
