- mindsdb_sql/parser/dialects/mindsdb/parser.py
- mindsdb_sql/parser/dialects/mysql/parser.py
- mindsdb_sql/parser/parser.py
- tests/test_parser/test_base_sql/test_select_structure.py
Resolves https://github.com/mindsdb/mindsdb_sql/issues/79
> Add LIMIT X,Y syntax support to parser

- mindsdb_sql/__about__.py
- mindsdb_sql/parser/dialects/mindsdb/create_integration.py
- mindsdb_sql/parser/dialects/mindsdb/create_predictor.py
- mindsdb_sql/parser/dialects/mindsdb/lexer.py
- mindsdb_sql/parser/dialects/mindsdb/parser.py
- tests/test_parser/test_mindsdb/test_create_integration.py
- tests/test_parser/test_mindsdb/test_create_predictor.py
Resolves #100 
Now the syntax looks like this:
```
CREATE PREDICTOR pred
FROM integration_name 
WITH 'select * FROM table'
AS ds_name
PREDICT f1 as f1_alias, f2
ORDER BY f_order_1 ASC, f_order_2, f_order_3 DESC
GROUP BY f_group_1, f_group_2
WINDOW 100
HORIZON 7
USING {"x": 1, "y": "a"}
```
Notice: no commas around JSON.
Create integration also changed to have no commas around JSON:
```
CREATE INTEGRATION db WITH ENGINE = 'mysql', PARAMETERS = {\"user\": \"admin\", \"password\": \"admin\"}
```
> Simplify create predictor syntax

- mindsdb_sql/parser/ast/__init__.py
- mindsdb_sql/parser/ast/insert.py
- mindsdb_sql/parser/dialects/mindsdb/lexer.py
- mindsdb_sql/parser/dialects/mindsdb/parser.py
- mindsdb_sql/parser/dialects/mysql/parser.py
- mindsdb_sql/parser/lexer.py
- mindsdb_sql/parser/parser.py
- tests/test_parser/test_base_sql/test_insert.py
#122 
Supported syntax for 3 dialects (sqlite, mysql, mindsdb):
- insert into table [(col,..)] values (expresion,..)[, (..)]
- insert into table [(col,..)] select_statement
#54
```
INSERT INTO mindsdb.predictor (name, predict, select_data_query, training_options) 
VALUES
(
'name',
'f1 as f1_alias, f2',
'select * FROM table',
'{{"join_learn_process": true, "stop_training_in_x_seconds": 3}}'
)
```
is parsed as:
```
Insert(table=Identifier(parts=['mindsdb', 'predictor'])
columns=[Identifier(parts=['name']), Identifier(parts=['predict']), Identifier(parts=['select_data_query']), Identifier(parts=['training_options'])]
values=[
[
Constant(value='name')
Constant(value='f1 as f1_alias, f2')
Constant(value='select * FROM table')
Constant(value='{{"join_learn_process": true, …
```
> Insert command

- mindsdb_sql/parser/ast/select/__init__.py
- mindsdb_sql/parser/ast/select/constant.py
- mindsdb_sql/parser/ast/set.py
- mindsdb_sql/parser/dialects/mindsdb/lexer.py
- mindsdb_sql/parser/dialects/mindsdb/parser.py
- mindsdb_sql/parser/dialects/mysql/parser.py
- mindsdb_sql/parser/lexer.py
- mindsdb_sql/parser/parser.py
- tests/test_parser/test_base_sql/test_misc_sql_queries.py
#123
1. removed support of 'set autocommit'
2. support of multiple vars in SET (mysql and mindsdb):
- 'SET [modifier] variable = expr [, variable = expr] ...' 
- modifiers: SESSION/GLOBAL/PERSIST/PERSIST_ONLY
3. support SET CAHRSET (mysql and mindsdb): 
- SET {CHARACTER SET | CHARSET} {'charset_name' | DEFAULT}
4. support SET TRANSACTION
- SET [GLOBAL | SESSION] TRANSACTION [ISOLATION LEVEL ...] [, ...]
> Advanced support of 'SET' statement

- mindsdb_sql/__about__.py
- mindsdb_sql/parser/dialects/mindsdb/create_database.py
- mindsdb_sql/parser/dialects/mindsdb/create_predictor.py
- mindsdb_sql/planner/query_planner.py
- tests/test_planner/test_join_predictor.py
Changes:
- Support params for model in where clause:
```
select * from int.tab1 a
join pred.1 p
where a.x=1 and p.x=1 and a.y=3 and p.a='' 
```
Is the same as:
```
select * from int.tab1 a
join pred.1 p
where a.x=1 and a.y=3 
using x=1, a='' 
```
Fixes:
- internal render fixes
- fix planning subquery whit 3 level table:
```
SELECT
home_rentals.rental_price AS real_price,
home_rentals_model.rental_price AS predicted_price
FROM
(
SELECT * FROM example_db.demo_data.home_rentals
WHERE number_of_rooms = 2
)
JOIN mindsdb.home_rentals_model
```
> Release 0.4.10

- mindsdb_sql/__about__.py
- mindsdb_sql/parser/ast/select/parameter.py
- mindsdb_sql/parser/dialects/mindsdb/lexer.py
- mindsdb_sql/parser/dialects/mindsdb/parser.py
- mindsdb_sql/planner/query_planner.py
- mindsdb_sql/planner/utils.py
- tests/test_parser/test_mindsdb/test_create_integration.py
- tests/test_parser/test_mindsdb/test_drop_datasource.py
- tests/test_planner/test_select_from_predictor.py
Changes:
1. support different integrations in simple select. These queries are supported now:
```
select * from model1 where x = (select id from integration1.table1 where a=1)
select * from integration2.table2 where x in (select id from integration1.table1 where a=1)
select (select id from integration1.table1 where a=1) as x from integration2.table2
```
2. Syntax sugar:
- 'create project aa' == 'create database aa'
- 'drop project aa' == 'drop database aa'
> Release 0.5.1

- mindsdb_sql/parser/ast/select/identifier.py
- mindsdb_sql/planner/utils.py
Added proper handling when using 
```
`select `table`.* from `table`
```
After running: 
```py
from mindsdb_sql.planner import query_planner
from mindsdb_sql import parse_sql
planner = query_planner.QueryPlanner(
parse_sql("""SELECT `models`.* FROM `models`""", dialect='mindsdb'),
integrations=['information_schema', 'mindsdb', 'files', 'bespoke'],
predictor_metadata=[],
default_namespace='mindsdb'
)
for step in planner.execute_steps():
print(step)
```
Output is: 
```py
FetchDataframeStep(step_num=0, references=[], result_data=None, integration=mindsdb, query=SELECT `models`.* FROM `models`, raw_query=None)
```
This fixes issue when running this query on mindsdb and returns models
Fixes: #272
> Fix for issue #272

- mindsdb_sql/__about__.py
- mindsdb_sql/parser/ast/select/identifier.py
- mindsdb_sql/planner/query_planner.py
- mindsdb_sql/planner/query_prepare.py
- mindsdb_sql/planner/steps.py
- tests/test_planner/test_integration_select.py
- tests/test_planner/test_select_from_predictor.py
Changes in planner:
- support regular update command in integration:
```
update integration.table set a=1 where b=2
```
- support delete command regular and with subselect:
```
delete from integration.table where a=2
```
If integration are different or this is API database,  this query splits to 2 SQLs in planner ('select' and 'delete')
```
delete from integration.table where a in (select id from integration.table where b=2)
```
> Release 0.6.4

- mindsdb_sql/parser/dialects/mindsdb/__init__.py
- mindsdb_sql/parser/dialects/mindsdb/create_predictor.py
- mindsdb_sql/parser/dialects/mindsdb/lexer.py
- mindsdb_sql/parser/dialects/mindsdb/parser.py
- tests/test_parser/test_mindsdb/test_create_predictor.py
First out of possibly many "typed" model types, which may help in simplifying UX downstream.
New syntax:
```sql
CREATE ANOMALY DETECTION MODEL alert_model
FROM integration_name (select * FROM table)
USING
confidence=0.5;
```
> [ENH] Add support for anomaly detection model creation

- mindsdb_sql/parser/dialects/mindsdb/knowledge_base.py
- mindsdb_sql/parser/dialects/mindsdb/parser.py
- tests/test_parser/test_mindsdb/test_knowledgebase.py
fix parser to allow for user to not specify storage in creation of knowledge base
also see PR https://github.com/mindsdb/mindsdb/pull/7886
> fix parser to allow no storage to be passed to knowledge base

- mindsdb_sql/__about__.py
- mindsdb_sql/parser/dialects/mindsdb/knowledge_base.py
- mindsdb_sql/parser/dialects/mindsdb/parser.py
- tests/test_parser/test_mindsdb/test_knowledgebase.py
Ie user doesn't need to specify a model in query
see:
https://github.com/mindsdb/mindsdb/pull/8464
> add support for default embedding model in kb. 

- mindsdb_sql/__about__.py
- mindsdb_sql/parser/dialects/mindsdb/knowledge_base.py
- mindsdb_sql/parser/dialects/mindsdb/parser.py
- tests/test_parser/test_mindsdb/test_knowledgebase.py
add support for default embedding model in kb.  (#331)
> add support for default embedding model in kb.  (#331)

- mindsdb_sql/__about__.py
- mindsdb_sql/parser/ast/select/native_query.py
- mindsdb_sql/parser/dialects/mindsdb/parser.py
- mindsdb_sql/planner/plan_join.py
- mindsdb_sql/planner/plan_join_ts.py
- mindsdb_sql/planner/query_planner.py
- mindsdb_sql/planner/steps.py
- mindsdb_sql/planner/ts_utils.py
- mindsdb_sql/planner/utils.py
- mindsdb_sql/render/sqlalchemy_render.py
- tests/test_parser/test_base_sql/test_select_structure.py
- tests/test_parser/test_base_sql/test_union.py
- tests/test_parser/test_mindsdb/test_timeseries.py
- tests/test_planner/test_injected_data.py
- tests/test_planner/test_integration_select.py
- tests/test_planner/test_join_predictor.py
- tests/test_planner/test_join_tables.py
- tests/test_planner/test_plan_union.py
- tests/test_planner/test_prepared_statement.py
- tests/test_planner/test_ts_predictor.py
- tests/test_render/test_sqlalchemyrender.py
Changes:
- Planner for api database: additional processing query fixes #320
- Call query only with 'where' and 'limit' in API database
- Perform other operations in executor 
- Union 3 and more tables  fixes #333
- Joins
- All steps after join combined to Query step
- Logic of joins moved to subclasses: for regular and TS join
- Unified join logic for 'model join table': it is moved to main join class 
- Support join TS model with #323
- render native query in sqlalchemy render
> Planner improvements

- mindsdb_sql/parser/ast/select/parameter.py
- mindsdb_sql/planner/plan_join.py
- mindsdb_sql/planner/utils.py
Fix join & traverse for https://github.com/mindsdb/mindsdb/pull/8524
> Planner fixes

- mindsdb_sql/planner/plan_join.py
- mindsdb_sql/render/sqlalchemy_render.py
- tests/test_planner/test_join_predictor.py
Fixes:
- #351
- renderer: get sqlalchemy object
-  alchemy_query = SqlalchemyRender(dialect).get_query(ast_query)
> Mapping 'using' variables to model 

- mindsdb_sql/parser/dialects/mindsdb/parser.py
- mindsdb_sql/parser/dialects/mysql/parser.py
- tests/test_parser/test_base_sql/test_show.py
Changes:
- accept any keywords in SHOW:
- SHOW aaa
- SHOW aaa bbb 
Fixes: #175: 
- support SHOW create something identifier 
- except [if not exist] option
- SHOW EVENTS
- simple SHOW ERRORS
- SHOW PROFILE/PROFILES
- simple SHOW GRANTS
> Update SHOW command

- mindsdb_sql/parser/ast/create.py
- mindsdb_sql/planner/query_planner.py
- mindsdb_sql/planner/steps.py
- mindsdb_sql/render/sqlalchemy_render.py
- tests/test_planner/test_integration_select.py
Changes:
1. Support planning create table (<columns>)
2. Support render table column types
> Planner: create empty table 

- mindsdb_sql/planner/plan_join_ts.py
- mindsdb_sql/planner/query_planner.py
- mindsdb_sql/planner/ts_utils.py
- mindsdb_sql/render/sqlalchemy_render.py
- tests/test_planner/test_integration_select.py
- tests/test_planner/test_join_predictor.py
- tests/test_planner/test_mindsdb_predictors_select.py
- tests/test_planner/test_plan_union.py
- tests/test_planner/test_prepared_statement.py
- tests/test_planner/test_select_from_predictor.py
- tests/test_planner/test_ts_predictor.py
Support query current_timestamp in query:
```sql
select current_timestamp from my_pg.branches
```
Changes:
- Render: use special functions instead of identifier
- Planner
- don't add aliases for selects from database
- remove alias for ts conditions, they will be copied to other TS queries
> No aliases to FetchDataframeStep

- mindsdb_sql/parser/dialects/mindsdb/parser.py
- tests/test_parser/test_base_sql/test_describe.py
Support `describe <object type> <object name>`
Object type could be: AGENT / JOB / SKILL and others
Example: 
```sql
DESCRIBE VIEW v1
``
> Support describe objects

- .github/workflows/pypi.yml
- .github/workflows/test.yml
- mindsdb_sql/parser/dialects/mindsdb/create_predictor.py
- mindsdb_sql/parser/dialects/mindsdb/parser.py
- setup.py
- tests/test_parser/test_base_sql/test_misc_sql_queries.py
- tests/test_parser/test_mindsdb/test_create_predictor.py
Changes:
- Support update active version of model
- `Set active model_name.11`
- Support optional database for CREATE/RETRAIN/FINETUNE model:
```sql
RETRAIN MODEL xxx from (select db_name.table)
```
> Parser updates 4.24

- mindsdb_sql/planner/plan_join.py
- mindsdb_sql/planner/steps.py
- tests/test_planner/test_join_predictor.py
Mapping columns to model in joins
In this example
```sql
select * from db.table1 t
join my_model m on t.a = m.x
```
If table1 has:
```
a | b | c 
---------
1 | 2 | 3 
```
Column 'a' will be renamed to 'x' and my_model will receive input:
```
x | b | c 
---------
1 | 2 | 3 
```
Related to https://github.com/mindsdb/mindsdb/issues/4576
> Model column mapping

- mindsdb_sql/parser/dialects/mindsdb/parser.py
- tests/test_parser/test_base_sql/test_update.py
Fix for supporting using in update from select 
```sql
UPDATE test_db.error_logs
SET ai_explanation = prediction_data.completion
FROM 
(
SELECT * FROM test_db.error_logs AS input
USING  aaa = "bbb" --  <--
) AS prediction_data
WHERE test_db.error_logs.id = prediction_data.id
```
> Fix update from select with using

- mindsdb_sql/parser/ast/insert.py
- mindsdb_sql/render/sqlalchemy_render.py
- tests/test_render/test_sqlalchemyrender.py
Changes:
- `get_exec_params` function:
- alternative to `get_string` function
- makes render query with params, output is sql and list of params: 
- insert into table values  (%s, %s)
- [[1,2], [3,4]]
- is_plain property of insert command
- if is set - render can use it to extract params
> Sqlalchemy render optimizations

- mindsdb_sql/planner/plan_join.py
- mindsdb_sql/planner/steps.py
- tests/test_planner/test_injected_data.py
- tests/test_planner/test_integration_select.py
- tests/test_planner/test_join_predictor.py
- tests/test_planner/test_join_tables.py
- tests/test_planner/test_mindsdb_predictors_select.py
Updated planner to support option to plan query with partitions
To enable it the 'partition_size' param should be used:
```sql
select * from int.tab1 a
join proj.pred1 p1          
using partition_size=1000   
```
It will:
- fetch all from `int.tab1`
- split data by 1000 rows chunks 
- execute ApplyPredictorStep and JoinStep for every chunk
For now only ApplyPredictorStep and JoinStep could be used in partition
> Predict in partitions

- mindsdb_sql/parser/dialects/mindsdb/lexer.py
- mindsdb_sql/parser/dialects/mindsdb/parser.py
- tests/test_parser/test_base_sql/test_select_structure.py
Fixing wrong precedence of 'not in' operator
fixes #384
> Fix precedence of 'not in'

- mindsdb_sql/parser/dialects/mindsdb/lexer.py
- mindsdb_sql/parser/dialects/mindsdb/parser.py
- tests/test_parser/test_base_sql/test_select_structure.py
New supported syntax:
- select date '1998-12-01'
- select '1998-12-01'::date
> Support different casting

- mindsdb_sql/parser/dialects/mindsdb/parser.py
- tests/test_parser/test_base_sql/test_select_operations.py
Parser: 
Support expression in order by clause:
```sql
select *
from tbl
order by a*b -- <--
```
> Support expressions in order_by

- mindsdb_sql/parser/dialects/mindsdb/lexer.py
- mindsdb_sql/parser/dialects/mindsdb/parser.py
- tests/test_parser/test_base_sql/test_base_sql.py
Fixes:
- fix quote is escaped by quote
- example `women''s soccer`
- fix double quoted part of identifier
- example `t2."var (k)"`
> Fixes parsing quotes

- mindsdb_sql/parser/ast/select/case.py
- mindsdb_sql/parser/dialects/mindsdb/parser.py
- mindsdb_sql/render/sqlalchemy_render.py
- tests/test_parser/test_base_sql/test_select_structure.py
Support `case`  without default value:
```sql
select 
case
when t2.position <> 1 then t2.position 
end
from t2
```
Support render case in sqlalchemy render
> Fix case statement

- mindsdb_sql/parser/dialects/mindsdb/parser.py
- mindsdb_sql/render/sqlalchemy_render.py
- tests/test_parser/test_base_sql/test_select_structure.py
- tests/test_render/test_sqlalchemyrender.py
Support identifier in qoutes
```sql
select account_id from "order"
```
> Support double-quoted identifier

- mindsdb_sql/parser/dialects/mindsdb/parser.py
- tests/test_parser/test_base_sql/test_select_structure.py
- tests/test_parser/test_mindsdb/test_selects.py
Changes:
- Support LAST as argument of function
Example:
```sql
SELECT * FROM t1 
where id > coalesce(last, 0)
```
Fixes:
- Fix precedence of '::' operator (type cast)
> Support LAST in function

- mindsdb_sql/parser/dialects/mindsdb/parser.py
- mindsdb_sql/planner/query_planner.py
- mindsdb_sql/render/sqlalchemy_render.py
- tests/test_parser/test_base_sql/test_insert.py
Fixed  insert from union:
```sql
INSERT INTO table1 (
SELECT * from table2 
UNION 
SELECT * from table3
)
```
Updated: parser, planner, render
Fix: https://linear.app/mindsdb/issue/BE-425/fix-insert-from-union
> Fix insert from union

- mindsdb_sql/parser/dialects/mindsdb/parser.py
Fix parsing query 
```sql
SELECT * FROM tbl WHERE Id % 10 = 0;
```
as:
```sql
SELECT * FROM tbl WHERE Id % (10 = 0);
```
fix: https://linear.app/mindsdb/issue/BE-428/sql-fix-modulo-precedence
> Fix modulo precedence

- mindsdb_sql/parser/ast/select/type_cast.py
- mindsdb_sql/parser/dialects/mindsdb/parser.py
- mindsdb_sql/parser/dialects/mysql/parser.py
- mindsdb_sql/parser/parser.py
- mindsdb_sql/render/sqlalchemy_render.py
- tests/test_parser/test_base_sql/test_select_structure.py
Supporting casting with two parameters in type
`CAST(a AS decimal(10, 1))`
Fixes: https://linear.app/mindsdb/issue/BE-434/supporting-casting-with-two-parameters-in-type
> Support CAST(a AS decimal(x, y))

- mindsdb_sql/planner/plan_join.py
- tests/test_planner/test_join_predictor.py
- tests/test_planner/test_join_tables.py
For the query:
```sql
select * from table1 t1
join table2 t2 on t1.id=t2.id
```
After getting data from t1, it is extracting unique ids from this data and uses this query to get data from second table:
```sql
select * from table2 where id in (<ids from previous step>)
```
Fixes: https://linear.app/mindsdb/issue/BE-436/optimize-join
> Optimize join tables from different databases

- mindsdb_sql/planner/plan_join.py
- mindsdb_sql/planner/query_planner.py
- mindsdb_sql/planner/query_prepare.py
- tests/test_planner/test_join_predictor.py
- tests/test_planner/test_join_tables.py
Support query:
```sql
with t1 as (
select * from int1.tbl1
)
select t1.id, t2.* from t1 
join int2.tbl2 t2 on t1.id>t2.id
```
fix: https://github.com/mindsdb/mindsdb/issues/4291
> Cte support

- mindsdb_sql/parser/ast/select/case.py
- mindsdb_sql/parser/ast/select/operation.py
- mindsdb_sql/parser/dialects/mindsdb/parser.py
- mindsdb_sql/planner/query_planner.py
- mindsdb_sql/render/sqlalchemy_render.py
- tests/test_parser/test_base_sql/test_select_structure.py
- tests/test_planner/test_integration_select.py
- ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED in window function
- simple form of case
- query with cte to one integration
> Parser fixes #1
